# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- checkout: self
  clean: true

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Application and Domain Unit Tests'

- task: DotNetCoreCLI@2
  displayName: 'Run Integration Tests'
  inputs:
    command: 'test'
    projects: '**/*IntegrationTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Run Infrastructure Integration tests'

- task: DotNetCoreCLI@2
  displayName: 'Run Functional tests'
  inputs:
    command: 'test'
    projects: '**/*FunctionalTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Run API Functional tests'